.DEFAULT_GOAL := help

INVOKE = $(shell ! command -v invoke &>/dev/null && echo poetry run) invoke

.PHONY: help
help:
	@$(INVOKE) --list

TASKS = \
	changelog \
	check \
	check-code-quality \
	check-dependencies \
	check-docs \
	check-types \
	clean \
	combine \
	coverage \
	docs \
	docs-deploy \
	docs-regen \
	docs-serve \
	format \
	release \
	setup \
	test

$(TASKS):
	@poetry run invoke $@ $(args)
